[project]
name = "inzynierka-169257"
version = "0.1.0"
description = "Emotion recognition using CNNs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "requests>=2.32.5",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "trackio>=0.6.0",
]
