[project]
name = "inzynierka-169257"
version = "0.2.0"
description = "Emotion recognition using CNNs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imagededup>=0.3.3.post2",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "opencv-contrib-python>=4.11.0.86",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
    "torchprofile>=0.0.4",
    "torchvision>=0.24.0",
    "trackio>=0.6.0",
]
